#!/usr/bin/env ruby

# This automation item will get the requested attribute from a keychain item

# Args:
#   Required
#     --account: Keychain account name
#   Optional
#     --keychain: Path to keychain to use, defaults to login keychain
#     --command: security command to run : defaults to find-internet-password
require 'stringio'

class Arguments
  attr_accessor :account
  attr_accessor :keychain

  def keychain
    @keychain ||= "/Users/jp/Library/Keychains/login.keychain"
  end

  def command=(value)
    @command = value.to_sym
  end

  def command
    @command ||= 'find-internet-password'
  end
end

def build_arguments(arguments)
  result = Arguments.new

  arguments.each do|argument|
    pair = argument.split(":")
    name = pair[0].gsub(/-/,"")
    value = pair[1]
    result.send "#{name}=", value
  end
  result
end

arguments = build_arguments(ARGV)

command = "sudo -u jp /usr/bin/security #{arguments.command} -w -a #{arguments.account} #{arguments.keychain}"

system(command)
